apiVersion: v1
kind: Namespace
metadata:
  name: boomap-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: boomap-system-admin
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - secrets
  - events
  - serviceaccounts
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - boos.mattmoor.io
  resources:
  - mutablemaps
  - immutablemaps
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boomap-controller
  namespace: boomap-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: boomap-controller-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: boomap-system-admin
subjects:
- kind: ServiceAccount
  name: boomap-controller
  namespace: boomap-system

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: immutablemaps.boos.mattmoor.io
spec:
  group: boos.mattmoor.io
  names:
    categories:
    - all
    - mattmoor
    kind: ImmutableMap
    plural: immutablemaps
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mutablemaps.boos.mattmoor.io
spec:
  group: boos.mattmoor.io
  names:
    categories:
    - all
    - mattmoor
    kind: MutableMap
    plural: mutablemaps
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: boomap-controller
  name: boomap-controller
  namespace: boomap-system
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: boomap-controller

---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: webhook
  name: webhook
  namespace: boomap-system
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    role: webhook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boomap-controller
  namespace: boomap-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boomap-controller
  template:
    metadata:
      labels:
        app: boomap-controller
    spec:
      containers:
      - args:
        - -logtostderr
        - -stderrthreshold
        - INFO
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/mattmoor-public/github.com/mattmoor/boo-maps/cmd/controller@sha256:1bec2ef6912f0d2391dadfbe1702467005266b1d25fc8531049a9fa460cc47df
        name: boomap-controller
      serviceAccountName: boomap-controller

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: boomap-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
      role: webhook
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: webhook
        role: webhook
    spec:
      containers:
      - env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/mattmoor-public/github.com/mattmoor/boo-maps/cmd/webhook@sha256:20fc4122d95a6186a24c964c8c4b8a05435c6d00985bd8849219cb70e12d3b23
        name: webhook
      serviceAccountName: boomap-controller

---
